In [1]:
# https://medium.com/dunder-data/selecting-subsets-of-data-in-pandas-6fcd0170be9c

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
tabla = pd.read_csv('E2_3D_F0.txt', delimiter='\t', skiprows=18, header=None, 
                   usecols=range(24))
tabla

0         1         2         3         4         5         6   \
0    XYDATA1  240.0000  245.0000  250.0000  255.0000  260.0000  265.0000   
1        250  243.4220    0.0000    0.0000    0.0000    0.0000    0.0000   
2        251  147.7220    0.0000    0.0000    0.0000    0.0000    0.0000   
3        252   88.5131    0.0000    0.0000    0.0000    0.0000    0.0000   
4        253   58.5342    0.0000    0.0000    0.0000    0.0000    0.0000   
..       ...       ...       ...       ...       ...       ...       ...   
147      396   34.7146   24.0361   19.8404   18.2831   18.0061   21.6931   
148      397   35.6042   24.9160   20.1008   17.8679   17.9576   21.0134   
149      398   35.8902   25.2825   20.2506   17.5917   17.7705   20.3869   
150      399   36.1975   24.9185   19.9447   17.9200   17.4324   19.6805   
151      400   36.6443   24.8142   20.1132   18.0498   17.2296   18.8465   

           7         8         9   ...         14         15         16  \
0    270.0000  275.0000  280.0000  ...  305.00000  310.00000  315.00000   
1      0.0000    0.0000    0.0000  ...    0.00000    0.00000    0.00000   
2      0.0000    0.0000    0.0000  ...    0.00000    0.00000    0.00000   
3      0.0000    0.0000    0.0000  ...    0.00000    0.00000    0.00000   
4      0.0000    0.0000    0.0000  ...    0.00000    0.00000    0.00000   
..        ...       ...       ...  ...        ...        ...        ...   
147   24.8205   24.1487   23.3547  ...    2.51955    2.11692    2.04140   
148   24.0698   23.6970   22.7701  ...    2.49453    2.11820    2.03742   
149   23.4513   23.2890   22.2280  ...    2.49650    2.13446    2.02279   
150   22.8174   23.0173   21.6444  ...    2.51309    2.18233    2.01207   
151   22.3682   22.4821   21.0398  ...    2.53514    2.21012    1.98718   

            17         18         19         20         21         22  \
0    320.00000  325.00000  330.00000  335.00000  340.00000  345.00000   
1      0.00000    0.00000    0.00000    0.00000    0.00000    0.00000   
2      0.00000    0.00000    0.00000    0.00000    0.00000    0.00000   
3      0.00000    0.00000    0.00000    0.00000    0.00000    0.00000   
4      0.00000    0.00000    0.00000    0.00000    0.00000    0.00000   
..         ...        ...        ...        ...        ...        ...   
147    2.11355    2.73878    3.39701    3.24041    3.24583    4.27608   
148    2.11199    2.74647    3.40923    3.26989    3.20430    4.04668   
149    2.10997    2.73708    3.41049    3.27512    3.15887    3.84407   
150    2.12339    2.69523    3.39495    3.28778    3.11535    3.66849   
151    2.13059    2.66395    3.35761    3.32328    3.07212    3.52525   

            23  
0    350.00000  
1      0.00000  
2      0.00000  
3      0.00000  
4      0.00000  
..         ...  
147    4.76376  
148    4.87431  
149    4.91890  
150    4.88334  
151    4.75603  

[152 rows x 24 columns]

In [5]:
nombres_filas = tabla[0][1:].values
nombres_filas

array(['250', '251', '252', '253', '254', '255', '256', '257', '258',
       '259', '260', '261', '262', '263', '264', '265', '266', '267',
       '268', '269', '270', '271', '272', '273', '274', '275', '276',
       '277', '278', '279', '280', '281', '282', '283', '284', '285',
       '286', '287', '288', '289', '290', '291', '292', '293', '294',
       '295', '296', '297', '298', '299', '300', '301', '302', '303',
       '304', '305', '306', '307', '308', '309', '310', '311', '312',
       '313', '314', '315', '316', '317', '318', '319', '320', '321',
       '322', '323', '324', '325', '326', '327', '328', '329', '330',
       '331', '332', '333', '334', '335', '336', '337', '338', '339',
       '340', '341', '342', '343', '344', '345', '346', '347', '348',
       '349', '350', '351', '352', '353', '354', '355', '356', '357',
       '358', '359', '360', '361', '362', '363', '364', '365', '366',
       '367', '368', '369', '370', '371', '372', '373', '374', '375',
       '376', '377',

In [6]:
nombres_columnas = tabla.loc[0][1:].values
nombres_columnas

array([240.0, 245.0, 250.0, 255.0, 260.0, 265.0, 270.0, 275.0, 280.0,
       285.0, 290.0, 295.0, 300.0, 305.0, 310.0, 315.0, 320.0, 325.0,
       330.0, 335.0, 340.0, 345.0, 350.0], dtype=object)

In [7]:
alternativa_nombre_filas = tabla.loc[1:,0].values
alternativa_nombre_filas

array(['250', '251', '252', '253', '254', '255', '256', '257', '258',
       '259', '260', '261', '262', '263', '264', '265', '266', '267',
       '268', '269', '270', '271', '272', '273', '274', '275', '276',
       '277', '278', '279', '280', '281', '282', '283', '284', '285',
       '286', '287', '288', '289', '290', '291', '292', '293', '294',
       '295', '296', '297', '298', '299', '300', '301', '302', '303',
       '304', '305', '306', '307', '308', '309', '310', '311', '312',
       '313', '314', '315', '316', '317', '318', '319', '320', '321',
       '322', '323', '324', '325', '326', '327', '328', '329', '330',
       '331', '332', '333', '334', '335', '336', '337', '338', '339',
       '340', '341', '342', '343', '344', '345', '346', '347', '348',
       '349', '350', '351', '352', '353', '354', '355', '356', '357',
       '358', '359', '360', '361', '362', '363', '364', '365', '366',
       '367', '368', '369', '370', '371', '372', '373', '374', '375',
       '376', '377',

In [8]:
solo_datos = tabla.loc[1:,1:] # sin primer fila y primer columna
primer_fila = tabla.loc[0,1:]
primer_columna = tabla.loc[1:,0]

In [9]:
solo_datos

1        2        3        4        5        6        7        8   \
1    243.4220   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   
2    147.7220   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   
3     88.5131   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   
4     58.5342   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   
5     45.3501   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   
..        ...      ...      ...      ...      ...      ...      ...      ...   
147   34.7146  24.0361  19.8404  18.2831  18.0061  21.6931  24.8205  24.1487   
148   35.6042  24.9160  20.1008  17.8679  17.9576  21.0134  24.0698  23.6970   
149   35.8902  25.2825  20.2506  17.5917  17.7705  20.3869  23.4513  23.2890   
150   36.1975  24.9185  19.9447  17.9200  17.4324  19.6805  22.8174  23.0173   
151   36.6443  24.8142  20.1132  18.0498  17.2296  18.8465  22.3682  22.4821   

          9        10  ...       14       15       16       17       18  \
1     0.0000   0.0000  ...  0.00000  0.00000  0.00000  0.00000  0.00000   
2     0.0000   0.0000  ...  0.00000  0.00000  0.00000  0.00000  0.00000   
3     0.0000   0.0000  ...  0.00000  0.00000  0.00000  0.00000  0.00000   
4     0.0000   0.0000  ...  0.00000  0.00000  0.00000  0.00000  0.00000   
5     0.0000   0.0000  ...  0.00000  0.00000  0.00000  0.00000  0.00000   
..       ...      ...  ...      ...      ...      ...      ...      ...   
147  23.3547  20.6585  ...  2.51955  2.11692  2.04140  2.11355  2.73878   
148  22.7701  20.1958  ...  2.49453  2.11820  2.03742  2.11199  2.74647   
149  22.2280  19.7751  ...  2.49650  2.13446  2.02279  2.10997  2.73708   
150  21.6444  19.3766  ...  2.51309  2.18233  2.01207  2.12339  2.69523   
151  21.0398  19.0780  ...  2.53514  2.21012  1.98718  2.13059  2.66395   

          19       20       21       22       23  
1    0.00000  0.00000  0.00000  0.00000  0.00000  
2    0.00000  0.00000  0.00000  0.00000  0.00000  
3    0.00000  0.00000  0.00000  0.00000  0.00000  
4    0.00000  0.00000  0.00000  0.00000  0.00000  
5    0.00000  0.00000  0.00000  0.00000  0.00000  
..       ...      ...      ...      ...      ...  
147  3.39701  3.24041  3.24583  4.27608  4.76376  
148  3.40923  3.26989  3.20430  4.04668  4.87431  
149  3.41049  3.27512  3.15887  3.84407  4.91890  
150  3.39495  3.28778  3.11535  3.66849  4.88334  
151  3.35761  3.32328  3.07212  3.52525  4.75603  

[151 rows x 23 columns]

In [10]:
primer_fila

1     240
2     245
3     250
4     255
5     260
6     265
7     270
8     275
9     280
10    285
11    290
12    295
13    300
14    305
15    310
16    315
17    320
18    325
19    330
20    335
21    340
22    345
23    350
Name: 0, dtype: object

In [11]:
primer_columna

1      250
2      251
3      252
4      253
5      254
      ... 
147    396
148    397
149    398
150    399
151    400
Name: 0, Length: 151, dtype: object

In [12]:
primer_columna.shape, primer_fila.shape, solo_datos.shape

((151,), (23,), (151, 23))

In [13]:
nuevo = solo_datos.rename(index=primer_columna, columns=primer_fila)
nuevo

240.0    245.0    250.0    255.0    260.0    265.0    270.0    275.0  \
250  243.4220   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   
251  147.7220   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   
252   88.5131   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   
253   58.5342   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   
254   45.3501   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   
..        ...      ...      ...      ...      ...      ...      ...      ...   
396   34.7146  24.0361  19.8404  18.2831  18.0061  21.6931  24.8205  24.1487   
397   35.6042  24.9160  20.1008  17.8679  17.9576  21.0134  24.0698  23.6970   
398   35.8902  25.2825  20.2506  17.5917  17.7705  20.3869  23.4513  23.2890   
399   36.1975  24.9185  19.9447  17.9200  17.4324  19.6805  22.8174  23.0173   
400   36.6443  24.8142  20.1132  18.0498  17.2296  18.8465  22.3682  22.4821   

       280.0    285.0  ...    305.0    310.0    315.0    320.0    325.0  \
250   0.0000   0.0000  ...  0.00000  0.00000  0.00000  0.00000  0.00000   
251   0.0000   0.0000  ...  0.00000  0.00000  0.00000  0.00000  0.00000   
252   0.0000   0.0000  ...  0.00000  0.00000  0.00000  0.00000  0.00000   
253   0.0000   0.0000  ...  0.00000  0.00000  0.00000  0.00000  0.00000   
254   0.0000   0.0000  ...  0.00000  0.00000  0.00000  0.00000  0.00000   
..       ...      ...  ...      ...      ...      ...      ...      ...   
396  23.3547  20.6585  ...  2.51955  2.11692  2.04140  2.11355  2.73878   
397  22.7701  20.1958  ...  2.49453  2.11820  2.03742  2.11199  2.74647   
398  22.2280  19.7751  ...  2.49650  2.13446  2.02279  2.10997  2.73708   
399  21.6444  19.3766  ...  2.51309  2.18233  2.01207  2.12339  2.69523   
400  21.0398  19.0780  ...  2.53514  2.21012  1.98718  2.13059  2.66395   

       330.0    335.0    340.0    345.0    350.0  
250  0.00000  0.00000  0.00000  0.00000  0.00000  
251  0.00000  0.00000  0.00000  0.00000  0.00000  
252  0.00000  0.00000  0.00000  0.00000  0.00000  
253  0.00000  0.00000  0.00000  0.00000  0.00000  
254  0.00000  0.00000  0.00000  0.00000  0.00000  
..       ...      ...      ...      ...      ...  
396  3.39701  3.24041  3.24583  4.27608  4.76376  
397  3.40923  3.26989  3.20430  4.04668  4.87431  
398  3.41049  3.27512  3.15887  3.84407  4.91890  
399  3.39495  3.28778  3.11535  3.66849  4.88334  
400  3.35761  3.32328  3.07212  3.52525  4.75603  

[151 rows x 23 columns]

In [14]:
nuevo.max(axis=0)

240.0    391.9340
245.0    179.0260
250.0    182.5680
255.0    266.6400
260.0    396.8990
265.0    645.2530
270.0    888.2710
275.0    930.0510
280.0    902.1670
285.0    762.9980
290.0    481.6290
295.0    144.0170
300.0     42.5386
305.0     63.6134
310.0     51.3859
315.0     42.5656
320.0     36.0521
325.0     48.2938
330.0     51.0004
335.0     41.9859
340.0     72.9942
345.0     74.7901
350.0     70.5227
dtype: float64

In [15]:
nuevo.max(axis=1)

250    243.4220
251    147.7220
252     88.5131
253     58.5342
254     45.3501
         ...   
396     34.7146
397     35.6042
398     35.8902
399     36.1975
400     36.6443
Length: 151, dtype: float64

In [16]:
nuevo.max()

240.0    391.9340
245.0    179.0260
250.0    182.5680
255.0    266.6400
260.0    396.8990
265.0    645.2530
270.0    888.2710
275.0    930.0510
280.0    902.1670
285.0    762.9980
290.0    481.6290
295.0    144.0170
300.0     42.5386
305.0     63.6134
310.0     51.3859
315.0     42.5656
320.0     36.0521
325.0     48.2938
330.0     51.0004
335.0     41.9859
340.0     72.9942
345.0     74.7901
350.0     70.5227
dtype: float64

In [17]:
(nuevo.max(axis=0)).max()

930.051

In [18]:
np_valores = nuevo.values

In [19]:
print(np_valores)

[[243.422     0.        0.      ...   0.        0.        0.     ]
 [147.722     0.        0.      ...   0.        0.        0.     ]
 [ 88.5131    0.        0.      ...   0.        0.        0.     ]
 ...
 [ 35.8902   25.2825   20.2506  ...   3.15887   3.84407   4.9189 ]
 [ 36.1975   24.9185   19.9447  ...   3.11535   3.66849   4.88334]
 [ 36.6443   24.8142   20.1132  ...   3.07212   3.52525   4.75603]]


In [20]:
np_valores.argmax(axis=0)

array([ 54,   5,  10,  53,  54,  52,  53,  53,  53,  53,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110])

In [21]:
np_valores.argmax(axis=1)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 2, 2, 0, 0, 3, 3, 3, 1, 1, 4, 4,
       1, 1, 2, 5, 5, 5, 5, 3, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
posmax = np.unravel_index(np_valores.argmax(axis=None), np_valores.shape)
posmax

(53, 7)

In [28]:
np_valores[53,7] == (nuevo.max(axis=0)).max()

True