In [1]:
import numpy as np

In [18]:
matriz = np.random.normal(size=(5000, 1000))

In [41]:
posicion = abs(matriz) <= 0.01

In [31]:
matriz.shape

(5000, 1000)

In [32]:
posicion.shape

(5000, 1000)

In [44]:
pos = np.unravel_index(np.argmax(posicion,axis=None), posicion.shape)

In [46]:
matriz[pos], pos

(-0.007317549276088264, (0, 153))

In [54]:
matriz[0:2,150:155]

array([[ 0.87158574,  1.36832008, -0.04855554, -0.00731755,  2.7896262 ],
       [-0.73199407,  1.95641293, -1.54386411, -1.73663421, -1.15090624]])

In [56]:
abs(matriz[0:2,150:155])

array([[0.87158574, 1.36832008, 0.04855554, 0.00731755, 2.7896262 ],
       [0.73199407, 1.95641293, 1.54386411, 1.73663421, 1.15090624]])

In [58]:
(abs(matriz[0:2,150:155]) <= 0.01)*1.0

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
pos = np.array(np.where(abs(matriz) < 0.001))

In [67]:
print(pos)

[[   1    4    5 ... 4993 4996 4997]
 [ 741  162  281 ...  111  381   47]]


In [69]:
pos.shape

(2, 4038)